### ISSUE TITLE
typo in command subhead

### ISSUE THREAD

**Issue by galaxiawu** [amir002001/goombot#5]
![CleanShot 2024-06-24 at 13 08 55@2x](https://github.com/amir002001/goombot/assets/49656471/68d569c8-463a-4a32-a802-93b81e5c6ace)
typo "what are you **up to** today!?"

**Comment by amir002001** [comment]
fixed in [1f322e8](https://github.com/amir002001/goombot/commit/1f322e826ca5b8255324c8719b867704d7a34ed0)
